app:
  firebase:
    key-location: './src/main/resources/credentials.json'
    env: 'local'

logging:
  file:
    name: app.log


spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER