app:
  firebase:
    enabled: true
    key-location: './src/main/resources/credentials.json'

logging:
  file:
    name: app.log


spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER