app:
  firebase:
    type: emulator
    projectId: "hackserver-9c717"

server:
  forward-headers-strategy: FRAMEWORK
  error:
    whitelabel:
      enabled: false

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus